/*
   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/

/* DMX512 transmitter for the Seeed XIAO ESP32-C6 + RS485 breakout (TP8485E).
 *
 * Ported from the Arduino sketch in the T8-7X-DMX project. The BREAK is generated by
 * inverting the idle-high TX line rather than by dropping the baud rate, because on this
 * exact board the usual alternatives are known to fail: esp_dmx hangs in
 * dmx_driver_install() (upstream issue #219, closed "not planned"), and the baud-switch
 * break silently misbehaves depending on the UART clock source.
 */

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <esp_err.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DMX_MAX_CHANNEL 512

/* Called from the DMX task immediately before each frame is rendered, with no lock held.
 * Used to advance time-based state (the Identify blink, the console address sweep). */
typedef void (*dmx512_frame_hook_t)(void);

/* Brings up UART1 at 250 kbaud 8N2, asserts DE, and starts the frame task. */
esp_err_t dmx512_init(void);

esp_err_t dmx512_register_frame_hook(dmx512_frame_hook_t hook);

/* Groups several slot writes into one frame. Without this, a mode change (which zeroes
 * CH3..CH43 and then writes the new colour channels) can be snapshotted half-done and put
 * one frame of garbage on the wire. The lock is recursive and must be released as often as
 * it is taken; never hold it across anything slow. */
void dmx512_lock(void);
void dmx512_unlock(void);

/* Channels are 1-based DMX slot numbers. Out-of-range channels are rejected. */
esp_err_t dmx512_set_slot(uint16_t channel, uint8_t value);
esp_err_t dmx512_set_slots(uint16_t first_channel, const uint8_t *values, size_t count);
esp_err_t dmx512_fill_slots(uint16_t first_channel, uint8_t value, size_t count);
uint8_t dmx512_get_slot(uint16_t channel);

/* Copies `count` slots starting at `first_channel` into `out`, atomically with respect to
 * frame rendering. Used by the console's `dump`. */
esp_err_t dmx512_get_slots(uint16_t first_channel, uint8_t *out, size_t count);

#ifdef __cplusplus
}
#endif
